spring:
  application:
    name: glint
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://glint.cjo8aqucgzfd.ap-southeast-2.rds.amazonaws.com:3306/glint?serverTimezone=Asia/Seoul
#    username: glint
#    password: Glint1q2w3e4r!!
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/glint?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1234
  jpa:
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
#        hbm2ddl.auto: create
        ddl-auto: update
        dialect: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true

  data:
    redis:
      host: localhost
      port: 6379

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    groups:
      enabled: true
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json


logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

server:
  servlet:
    context-path: /glint
---
spring:
  config:
    activate:
      on-profile: local
  application:
    name: glint
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/glint?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1234
  jpa:
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        #        hbm2ddl.auto: create
        ddl-auto: update
        dialect: org.hibernate.dialect.MySQLDialect
    generate-ddl: true
  data:
    redis:
      host: localhost
      port: 6379
---
spring:
  config:
    activate:
      on-profile: release
    import: aws-parameterstore:/config/glint/
  application:
    name: glint
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${jdbc.url}
    username: ${jdbc.username}
    password: ${jdbc.password}

  jpa:
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        #        hbm2ddl.auto: create
        ddl-auto: none
        dialect: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: false

  data:
    redis:
      host: ${cache.url}
      port: 6379


